"""empty message

Revision ID: 019d7025e655
Revises: 93c897381774
Create Date: 2021-08-29 15:35:48.708742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019d7025e655'
down_revision = '93c897381774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Genre', sa.Column('name', sa.String(length=120), nullable=True))
    op.drop_column('Genre', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Genre', sa.Column('genre', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('Genre', 'name')
    # ### end Alembic commands ###
