"""empty message

Revision ID: 8bbd48b01fa4
Revises: ec346fca5723
Create Date: 2021-08-30 15:22:55.754089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bbd48b01fa4'
down_revision = 'ec346fca5723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.drop_column('Show', 'name')
    op.add_column('Venue', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'created_date')
    op.add_column('Show', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('Artist', 'created_date')
    # ### end Alembic commands ###
