"""empty message

Revision ID: 93c897381774
Revises: fb7c7348a6c9
Create Date: 2021-08-27 21:33:41.074054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c897381774'
down_revision = 'fb7c7348a6c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('name', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'name')
    # ### end Alembic commands ###
